name = "lighthouse100-theme"
license = "MIT"
licenselink = "https://github.com/hkwk/lighthouse100-theme/blob/master/LICENSE"
description = "A Lighthouse scored 100 theme"
tags = ["blog", "company"]
features = ["blog", "themes", "hkwk"]
min_version = 0.21
	
[author]
    name = "HKL"
    homepage = "https://xou.net"

